#!/usr/bin/env bash
# conform-project.sh — bring a repo into the Innotel Platform Stack conformity standard,
# or audit an existing repo against it.
#
# Usage:
#   ./scripts/conform-project.sh <repo-dir>                 # audit
#   ./scripts/conform-project.sh --new <name> <classification>   # scaffold
#
# The standard lives in innotel-platform-stack/docs/standard.md.

set -euo pipefail

OWNER="innotelinc"
ACTOR="Darnel Hunter"
EMAIL="dhunter@innotel.us"
YEAR="$(date +%Y)"

# ── helpers ────────────────────────────────────────────────────────────────────

need() { printf 'conform: %s\n' "$*"; }

die() {
  printf 'conform: error: %s\n' "$*" >&2
  exit 1
}

heading() { printf '\n==> %s\n' "$*"; }

github_url() {
  printf 'https://github.com/%s/%s' "$OWNER" "$1"
}

pages_url() {
  printf 'https://innotelinc.github.io/%s/' "$1"
}

license_badge() {
  case "${1:-MIT}" in
    MIT)         printf '[![License: MIT](https://img.shields.io/badge/license-MIT-blue.svg)](LICENSE)' ;;
    AGPL-3.0-or-later) printf '[![License: AGPL-3.0-or-later](https://img.shields.io/badge/license-AGPL--3.0-or-later-brightgreen.svg)](LICENSE)' ;;
    *)           printf '[![License: %s](https://img.shields.io/badge/license-%s-brightgreen.svg)](LICENSE)' "$1" "$1" ;;
  esac
}

# ── attribution guard + hooks (shared verbatim across repos) ──────────────────

write_guard_lib() {
  cat > "$1/.githooks/guard-lib" <<'GUARD_EOF'
#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# guard-lib — shared patterns + helpers for the attribution guard.
# Sourced by .githooks/commit-msg, .githooks/pre-commit, and the CI workflow
# (.github/workflows/attribution-guard.yml), so one copy of the policy lives
# in every repo and every enforcement point uses the exact same rules.
#
# Policy (content only — never inspects author/committer identity):
#   Attribution text must credit nobody but Darnel Hunter <dhunter@innotel.us>.
#   Concretely the guard rejects:
#     1. git-trailer credit lines (Co-Authored-By, Signed-off-by, ...) whose
#        value is not one of Darnel Hunter's known identities, and
#     2. any line that credits an AI assistant / tool in an attribution
#        phrase (co-author trailers, "Generated with/by X", credit lines).
#   Plain product prose that merely names a technology (an "OpenAI-compatible
#   endpoint", "generated by the release pipeline") is NOT attribution and is
#   allowed.
#
# NOTE: keep this file free of literal attribution strings naming a tool or
# person other than Darnel — the guard scans added lines, including its own
# additions, and must never reject itself. Patterns are assembled below from
# the TOOL_TOKEN variable for exactly this reason.
# ═══════════════════════════════════════════════════════════════════════════

# The only person who may ever be credited. If Darnel commits under another
# address someday, extend this list — do not loosen the non-Darnel rules.
ALLOWED_ATTRIBUTIONS=(
  'Darnel Hunter <dhunter@innotel.us>'
  'Darnel Hunter <darnelhunter@gmail.com>'
  'Darnel Hunter <68697450+innotelinc@users.noreply.github.com>'
  # GitHub's own dependency bot — its automated commits carry a Signed-off-by.
  'dependabot[bot] <support@github.com>'
)

# Git-trailer credit prefixes (case-insensitive, ERE as used by grep -E).
# A line beginning with one of these is an attribution and must name Darnel.
TRAILER_PREFIXES='co-authored-by|signed-off-by|authored-by|helped-by|co-developed-by|based-on-patch-by|reviewed-by|tested-by|reported-by'

# AI assistant/tool tokens. Each token appears ONLY inside an attribution
# phrase below — never as a bare word — so product docs that mention a
# technology (e.g. an OpenAI-compatible endpoint) never trip the guard.
TOOL_TOKEN='codebuff|claude|anthropic|copilot|chatgpt|openai|gemini|bard|aider|cursor|windsurf'

# Attribution phrases naming an AI assistant/tool. Matching is substring-wide
# (grep -E scans the whole line), so emoji either side of the phrase is caught
# by the same pattern. Case-insensitive. The tool tokens are interpolated at
# runtime so the source text stays self-clean.
FORBIDDEN_PATTERNS=(
  "co-authored-by:[[:space:]]*[^<]*(${TOOL_TOKEN})"
  "co-authored-by:[[:space:]]*[^<]*([0-9a-z]\\\\.)?ai[[:space:]<,]"
  "(generated|created|authored|written|built|developed|made|powered|maintained)[[:space:]]+[bw]y[[:space:]]+[^.,;]*(${TOOL_TOKEN})"
  "(generated|created|authored|written|built|developed|made|powered)[[:space:]]+with[[:space:]]+[^.,;]*(${TOOL_TOKEN})"
  "(generated|created|authored|written|built|developed|made|powered)[[:space:]]+(using|via)[[:space:]]+[^.,;]*(${TOOL_TOKEN})"
  "co-authored-by:[[:space:]]*[^<]*noreply@(${TOOL_TOKEN%|*}|codebuff)(\\\\.ai|\\\\.com|\\\\.org)"
  "(${TOOL_TOKEN})[[:space:]]+<noreply@"
  "(credit|credits|thanks|acknowledg)[[:space:]]*:?[[:space:]]*(to[[:space:]]+)?(${TOOL_TOKEN})"
)

# Scan text on stdin; exit 0 if clean, 1 (printing a reason) if any
# attribution is found. Reads stdin ONCE into a variable first — each grep in
# FORBIDDEN_PATTERNS runs against that single in-memory copy.
guard_check_stream() {
  local input
  input="$(cat)"

  # 1. Git-trailer credit lines must name an allowed attribution.
  if printf '%s\n' "$input" | grep -Eiq "^(${TRAILER_PREFIXES})[[:space:]]*:"; then
    local bad
    bad="$(printf '%s\n' "$input" | grep -Eia "^(${TRAILER_PREFIXES})[[:space:]]*:[[:space:]]*[^${ALLOWED_ATTRIBUTIONS[0]}]" || true)"
    if [ -n "$bad" ]; then
      printf '%s\n' "$bad" | sed 's/^/guard: bad trailer:/' >&2
      return 1
    fi
  fi

  # 2. AI-assistant attribution phrases are forbidden.
  for pattern in "${FORBIDDEN_PATTERNS[@]}"; do
    if printf '%s\n' "$input" | grep -Eiq -- "$pattern"; then
      printf 'guard: forbidden attribution pattern matched: %s\n' "$pattern" >&2
      return 1
    fi
  done

  return 0
}
GUARD_EOF
}

write_commit_msg_hook() {
  cat > "$1/.githooks/commit-msg" <<'COMMIT_MSG_EOF'
#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# commit-msg — block attribution in the commit MESSAGE.
#
# Runs with the message file as $1 (the authoritative, final message including
# any trailers a tool appended). Catches credit trailers and "Generated by …"
# lines before the commit is written. Policy: only Darnel Hunter
# <dhunter@innotel.us> may ever be credited. Pairs with the pre-commit hook,
# which guards the committed files themselves.
#
# Install (enables the guard locally):
#     git config core.hooksPath .githooks
# setup.sh on a fresh install already does this.
# ═══════════════════════════════════════════════════════════
set -uo pipefail

MSG_FILE="${1:-}"
HOOK_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=.githooks/guard-lib
# shellcheck disable=SC1091
source "$HOOK_DIR/guard-lib"

say() { printf 'guard: %s\n' "$*"; }

if [ -z "$MSG_FILE" ] || [ ! -f "$MSG_FILE" ]; then
  say "warning: no commit message file given — skipping message guard"
  exit 0
fi

if ! guard_check_stream < "$MSG_FILE"; then
  say "commit blocked: the message contains attribution to someone other than Darnel Hunter <dhunter@innotel.us>."
  exit 1
fi
exit 0
COMMIT_MSG_EOF
}

write_pre_commit_hook() {
  cat > "$1/.githooks/pre-commit" <<'PRE_COMMIT_EOF'
#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# pre-commit — block attribution from landing in committed FILES.
#
# The message/trailer is enforced by the sibling commit-msg hook (the message
# isn't written until later); this hook scans the staged diff so any
# attribution added to docs, READMEs, credits, or comments in the tree itself
# is rejected before the commit can be created. Policy: only Darnel Hunter
# <dhunter@innotel.us> may ever be credited.
#
# Install (enables the guard locally):
#     git config core.hooksPath .githooks
# setup.sh on a fresh install already does this.
# ═══════════════════════════════════════════════════════════
set -uo pipefail

HOOK_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=.githooks/guard-lib
# shellcheck disable=SC1091
source "$HOOK_DIR/guard-lib"

say() { printf 'guard: %s\n' "$*"; }

# Scan only the ADDED lines of the staged diff (never the unchanged context).
added="$(git diff --cached --no-color -U0 2>/dev/null | grep '^+' | grep -v '^+++' || true)"
if [ -n "$added" ]; then
  if ! printf '%s\n' "$added" | guard_check_stream; then
    say "commit blocked: the staged changes introduce attribution to someone other than Darnel Hunter <dhunter@innotel.us>."
    exit 1
  fi
fi
exit 0
PRE_COMMIT_EOF
}

write_attribution_guard_ci() {
  cat > "$1/.github/workflows/attribution-guard.yml" <<'AG_EOF'
# ═══════════════════════════════════════════════════════════════════════════
# attribution-guard.yml — enforce the attribution policy on every push and PR.
#
# Policy: no credit is given to anyone but Darnel Hunter <dhunter@innotel.us>.
# The guard rejects attribution text (Co-Authored-By/Signed-off-by trailers
# naming anyone else, "Generated with/by <AI tool>", credit lines) in:
#   - commit messages introduced by this push/PR,
#   - the PR title/body (pull requests),
#   - lines added to any file in the push/PR.
#
# The actual patterns live in .githooks/guard-lib (shared with the local
# commit-msg/pre-commit hooks), so this workflow just sources that file and
# feeds it the streams above. It never inspects author/committer identity.
# ═══════════════════════════════════════════════════════════════════════════

name: Attribution guard

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read

jobs:
  guard:
    name: Check attribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commit messages, PR text, and file changes
        env:
          BASE_SHA: ${{ github.event.before }}
          HEAD_SHA: ${{ github.sha }}
          PR_BASE: ${{ github.event.pull_request.base.sha }}
          PR_HEAD: ${{ github.event.pull_request.head.sha }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
          REF_TYPE: ${{ github.ref_type }}
        run: |
          set -uo pipefail
          source .githooks/guard-lib

          fail=0

          # ── Tag pushes introduce no new history ───────────────────────
          # A tag push carries an all-zero "before" SHA (like a brand-new
          # repo), but the tag itself adds only the tagged commit. Scan the
          # tag's own commit message + diff instead of the full history, so
          # historical trailers never block a release.
          if [ "${REF_TYPE:-}" = "tag" ]; then
            git log -1 --format=%B "${GITHUB_REF_NAME}" | guard_check_stream || fail=1
            added="$(git show --format= --no-color -U0 "${GITHUB_REF_NAME}" -- . 2>/dev/null | grep '^+' | grep -v '^+++' || true)"
            if [ -n "$added" ]; then
              printf '%s\n' "$added" | guard_check_stream || fail=1
            fi
            if [ "$fail" -ne 0 ]; then
              echo "::error::Attribution guard failed — only Darnel Hunter <dhunter@innotel.us> may be credited."
              exit 1
            fi
            echo "attribution guard: clean"
            exit 0
          fi

          # ── Determine the commit range to scan ─────────────────────────
          if [ "${GITHUB_EVENT_NAME:-}" = "pull_request" ]; then
            base="${PR_BASE:-}"; head="${PR_HEAD:-}"
          else
            base="${BASE_SHA:-}"; head="${HEAD_SHA:-}"
          fi
          # A brand-new branch/repo pushes with an all-zero "before" SHA —
          # in that case scan the full reachable history instead.
          if [ -n "$base" ] && printf '%s' "$base" | grep -Eq '^0+$'; then
            base=""
          fi

          # ── 1. Commit messages in the range ───────────────────────────
          if [ -n "$base" ] && [ -n "$head" ]; then
            git log --format=%B "${base}..${head}" | guard_check_stream || fail=1
          else
            git log --format=%B | guard_check_stream || fail=1
          fi

          # ── 2. PR title + body (content check only) ───────────────────
          if [ "${GITHUB_EVENT_NAME:-}" = "pull_request" ]; then
            { printf '%s\n' "${PR_TITLE:-}"; printf '%s\n' "${PR_BODY:-}"; } | guard_check_stream || fail=1
          fi

          # ── 3. Lines added to files in the push/PR ────────────────────
          added=""
          if [ -n "$base" ] && [ -n "$head" ]; then
            added="$(git diff --no-color -U0 "$base" "$head" -- . 2>/dev/null | grep '^+' | grep -v '^+++' || true)"
          else
            added="$(git log -p --format= --no-color HEAD 2>/dev/null | grep '^+' | grep -v '^+++' || true)"
          fi
          if [ -n "$added" ]; then
            printf '%s\n' "$added" | guard_check_stream || fail=1
          fi

          if [ "$fail" -ne 0 ]; then
            echo "::error::Attribution guard failed — only Darnel Hunter <dhunter@innotel.us> may be credited."
            exit 1
          fi
          echo "attribution guard: clean"
AG_EOF
}

write_ci_yml() {
  cat > "$1/.github/workflows/ci.yml" <<'CI_EOF'
# ═══════════════════════════════════════════════════════════════════════════
# ci.yml — static checks on push and pull requests.
#
# The repo is maintained at zero findings: structure, compose, hooks, and the
# landing page stay conformant. Attribution guard lives in its own workflow.
# ═══════════════════════════════════════════════════════════════════════════

name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  structure:
    name: Repository structure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Conformant structure
        run: |
          set -euo pipefail
          for f in README.md LICENSE .env.example web/landing/index.html; do
            if [ ! -f "$f" ]; then
              echo "::error::missing required file: $f"
              exit 1
            fi
          done
          echo "structure: ok"

      - name: .gitignore covers .env
        run: |
          set -euo pipefail
          if ! grep -q '^\.env' .gitignore; then
            echo "::warning:: .gitignore does not list .env"
          fi

  landing:
    name: Landing page sanity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Landing sanity
        run: |
          set -euo pipefail
          f=web/landing/index.html
          grep -qi '<title>' "$f" || { echo "::error::landing has no <title>"; exit 1; }
          grep -qi 'og:title' "$f" || { echo "::error::landing has no og:title"; exit 1; }
          echo "landing: ok"
CI_EOF
}

write_pages_yml() {
  cat > "$1/.github/workflows/pages.yml" <<'PAGES_EOF'
# Publish the project landing page (web/landing/) to GitHub Pages.
#
#   https://innotelinc.github.io/<repo>/  (landing, static)
#
# Requires Pages to be enabled once: repo Settings -> Pages -> Source:
# "GitHub Actions" (this workflow also attempts to enable it automatically).
# After that, every push to main that touches web/landing republishes.
# workflow_dispatch works too.

name: GitHub Pages

on:
  push:
    # [main, master]: repos default to either branch across the portfolio.
    branches: [main, master]
    paths:
      - "web/landing/**"
      - ".github/workflows/pages.yml"
  workflow_dispatch:

# Cancel any in-flight publish for the same ref; a Pages deploy is atomic.
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/landing

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
PAGES_EOF
}

write_makefile() {
  local name="$1" classification="$2"
  cat > "$1/Makefile" <<MAKEFILE_EOF
# ==========================================================================
# ${name} — operator workflow
# Usage: make <target>   (see \`make help\`)
# ==========================================================================

.DEFAULT_GOAL := help
SHELL := /bin/bash

.PHONY: help setup up down logs ps \\
        check:commits check:compose

help: ## Show this help message
\t@echo "${name} — operator workflow"
\t@echo "Usage: make <target>"
\t@grep -E '^[a-zA-Z_:-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \\033[36m%-16s\\033[0m %s\\n", $$1, $$2}'

## ---- Bootstrap ------------------------------------------------------------

setup: ## Preflight, install guard hooks, generate .env secrets
\tbash scripts/setup.sh

## ---- Compose (this repo's services) -------------------------------------

up: ## Start all ${name}-managed services
\tdocker compose up -d

down: ## Stop ${name}-managed services (keeps volumes)
\tdocker compose down

logs: ## Tail logs from ${name}-managed services
\tdocker compose logs -f

ps: ## List service status
\tdocker compose ps

## ---- Conformity -----------------------------------------------------------

check:commits: ## Run the attribution guard over recent commit messages
\tbash .githooks/commit-msg .git/COMMIT_EDITMSG 2>/dev/null || true

check:compose: ## Validate the root compose file against .env.example
\tcp .env.example .env
\tdocker compose config --quiet
\trm -f .env
MAKEFILE_EOF
}

write_env_example() {
  local classification="$1"
  cat > "$1/.env.example" <<ENV_EOF
[TEMPLATE]
# ==========================================================================
# ${2} — environment configuration template
# Copy to \`.env\` (or run ./scripts/setup.sh) and fill in real values.
# Never commit \`.env\`. Production secrets come from Infisical (SecretOps).
# ==========================================================================

# --- General ----------------------------------------------------------------
APP_NAME=${2}
# Public hosts (DNS + TLS provisioned by Cerulean / NPM Edge)
BASE_DOMAIN=${3}

# --- OmniRoute (model gateway — OpenAI-compatible, single provider pool) ----
OMNIROUTE_BASE_URL=http://127.0.0.1:20128/v1
OMNIROUTE_API_KEY=change-me-omniroute-api-key
OMNIROUTE_MODEL=auto

# --- Authentik (OIDC identity provider — Cerulean's Authentik) --------------
OIDC_ISSUER_URL=https://auth.cerulean.innotel.us/application/o/${4}/
OIDC_CLIENT_ID=${4}
OIDC_CLIENT_SECRET=change-me-oidc-client-secret
OIDC_REDIRECT_URI=https://${3}/api/auth/callback

# --- Cerulean (TrustOps — DNS / NPM hosts / TLS) ----------------------------
CERULEAN_DNS_API_URL=http://127.0.0.1:3003
CERULEAN_ADMIN_PASSWORD=change-me-cerulean-admin
CERULEAN_ZONE=innotel.us

# --- Infisical (SecretOps) --------------------------------------------------
INFISICAL_ENCRYPTION_KEY=
INFISICAL_AUTH_SECRET=
INFISICAL_DB_PASSWORD=
INFISICAL_ORG=Innotel

# --- Magnate billing (RevenueOps — optional paid seats) ---------------------
MAGNATE_URL=https://magnate.innotel.us
ENTITLEMENTS_API_TOKEN=
# When set, must equal Magnate's ENTITLEMENTS_API_TOKEN.
# Empty = billing APIs are open on a trusted net.
ENV_EOF
}

write_license() {
  local license="$1"
  if [ "$license" = "MIT" ]; then
    cat > "$1/LICENSE" <<'MIT_EOF'
MIT License

Copyright (c) ${YEAR} Innotel Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
MIT_EOF
  else
    # Full canonical AGPL-3.0 text — GitHub license detection returns
    # NOASSERTION for short notices, which breaks repo license badges.
    cat > "$1/LICENSE" <<'AGPL_EOF'
                    GNU AFFERO GENERAL PUBLIC LICENSE
                       Version 3, 19 November 2007

 Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.

                            Preamble

  The GNU Affero General Public License is a free, copyleft license for
software and other kinds of works, specifically designed to ensure
cooperation with the community in the case of network server software.

  The licenses for most software and other practical works are designed
to take away your freedom to share and change the works.  By contrast,
our General Public Licenses are intended to guarantee your freedom to
share and change all versions of a program--to make sure it remains free
software for all its users.

  When we speak of free software, we are referring to freedom, not
price.  Our General Public Licenses are designed to make sure that you
have the freedom to distribute copies of free software (and charge for
them if you wish), that you receive source code or can get it if you
want it, that you can change the software or use pieces of it in new
free programs, and that you know you can do these things.

  Developers that use our General Public Licenses protect your rights
with two steps: (1) assert copyright on the software, and (2) offer
you this License which gives you legal permission to copy, distribute
and/or modify the software.

  A secondary benefit of defending all users' freedom is that
improvements made in alternate versions of the program, if they
receive widespread use, become available for other developers to
incorporate.  Many developers of free software are heartened and
encouraged by the resulting cooperation.  However, in the case of
software used on network servers, this result may fail to come about.
The GNU General Public License permits making a modified version and
letting the public access it on a server without ever releasing its
source code to the public.

  The GNU Affero General Public License is designed specifically to
ensure that, in such cases, the modified source code becomes available
to the community.  It requires the operator of a network server to
provide the source code of the modified version running there to the
users of that server.  Therefore, public use of a modified version, on
a publicly accessible server, gives the public access to the source
code of the modified version.

  An older license, called the Affero General Public License and
published by Affero, was designed to accomplish similar goals.  This is
a different license, not a version of the Affero GPL, but Affero has
released a new version of the Affero GPL which permits relicensing under
this license.

  The precise terms and conditions for copying, distribution and
modification follow.

                       TERMS AND CONDITIONS

  0. Definitions.

  "This License" refers to version 3 of the GNU Affero General Public License.

  "Copyright" also means copyright-like laws that apply to other kinds of
works, such as semiconductor masks.

  "The Program" refers to any copyrightable work licensed under this
License.  Each licensee is addressed as "you".  "Licensees" and
"recipients" may be individuals or organizations.

  To "modify" a work means to copy from or adapt all or part of the work
in a fashion requiring copyright permission, other than the making of an
exact copy.  The resulting work is called a "modified version" of the
earlier work or a work "based on" the earlier work.

  A "covered work" means either the unmodified Program or a work based
on the Program.

  To "propagate" a work means to do anything with it that, without
permission, would make you directly or secondarily liable for
infringement under applicable copyright law, except executing it on a
computer or modifying a private copy.  Propagation includes copying,
distribution (with or without modification), making available to the
public, and in some countries other activities as well.

  To "convey" a work means any kind of propagation that enables other
parties to make or receive copies.  Mere interaction with a user through
a computer network, with no transfer of a copy, is not conveying.

  An interactive user interface displays "Appropriate Legal Notices"
to the extent that it includes a convenient and prominently visible
feature that (1) displays an appropriate copyright notice, and (2)
tells the user that there is no warranty for the work (except to the
extent that warranties are provided), that licensees may convey the
work under this License, and how to view a copy of this License.  If
the interface presents a list of user commands or options, such as a
menu, a prominent item in the list meets this criterion.

  1. Source Code.

  The "source code" for a work means the preferred form of the work
for making modifications to it.  "Object code" means any non-source
form of a work.

  A "Standard Interface" means an interface that either is an official
standard defined by a recognized standards body, or, in the case of
interfaces specified for a particular programming language, one that
is widely used among developers working in that language.

  The "System Libraries" of an executable work include anything, other
than the work as a whole, that (a) is included in the normal form of
packaging a Major Component, but which is not part of that Major
Component, and (b) serves only to enable use of the work with that
Major Component, or to implement a Standard Interface for which an
implementation is available to the public in source code form.  A
"Major Component", in this context, means a major essential component
(kernel, window system, and so on) of the specific operating system
(if any) on which the executable work runs, or a compiler used to
produce the work, or an object code interpreter used to run it.

  The "Corresponding Source" for a work in object code form means all
the source code needed to generate, install, and (for an executable
work) run the object code and to modify the work, including scripts to
control those activities.  However, it does not include the work's
System Libraries, or general-purpose tools or generally available free
programs which are used unmodified in performing those activities but
which are not part of the work.  For example, Corresponding Source
includes interface definition files associated with source files for
the work, and the source code for shared libraries and dynamically
linked subprograms that the work is specifically designed to require,
such as by intimate data communication or control flow between those
subprograms and other parts of the work.

  The Corresponding Source need not include anything that users
can regenerate automatically from other parts of the Corresponding
Source.

  The Corresponding Source for a work in source code form is that
same work.

  2. Basic Permissions.

  All rights granted under this License are granted for the term of
copyright on the Program, and are irrevocable provided the stated
conditions are met.  This License explicitly affirms your unlimited
permission to run the unmodified Program.  The output from running a
covered work is covered by this License only if the output, given its
content, constitutes a covered work.  This License acknowledges your
rights of fair use or other equivalent, as provided by copyright law.

  You may make, run and propagate covered works that you do not
convey, without conditions so long as your license otherwise remains
in force.  You may convey covered works to others for the sole purpose
of having them make modifications exclusively for you, or provide you
with facilities for running those works, provided that you comply with
the terms of this License in conveying all material for which you do
not control copyright.  Those thus making or running the covered works
for you must do so exclusively on your behalf, under your direction
and control, on terms that prohibit them from making any copies of
your copyrighted material outside their relationship with you.

  Conveying under any other circumstances is permitted solely under
the conditions stated below.  Sublicensing is not allowed; section 10
makes it unnecessary.

  3. Protecting Users' Legal Rights From Anti-Circumvention Law.

  No covered work shall be deemed part of an effective technological
measure under any applicable law fulfilling obligations under article
11 of the WIPO copyright treaty adopted on 20 December 1996, or
similar laws prohibiting or restricting circumvention of such
measures.

  When you convey a covered work, you waive any legal power to forbid
circumvention of technological measures to the extent such circumvention
is effected by exercising rights under this License with respect to
the covered work, and you disclaim any intention to limit operation or
modification of the work as a means of enforcing, against the work's
users, your or third parties' legal rights to forbid circumvention of
technological measures.

  4. Conveying Verbatim Copies.

  You may convey verbatim copies of the Program's source code as you
receive it, in any medium, provided that you conspicuously and
appropriately publish on each copy an appropriate copyright notice;
keep intact all notices stating that this License and any
non-permissive terms added in accord with section 7 apply to the code;
keep intact all notices of the absence of any warranty; and give all
recipients a copy of this License along with the Program.

  You may charge any price or no price for each copy that you convey,
and you may offer support or warranty protection for a fee.

  5. Conveying Modified Source Versions.

  You may convey a work based on the Program, or the modifications to
produce it from the Program, in the form of source code under the
terms of section 4, provided that you also meet all of these conditions:

    a) The work must carry prominent notices stating that you modified
    it, and giving a relevant date.

    b) The work must carry prominent notices stating that it is
    released under this License and any conditions added under section
    7.  This requirement modifies the requirement in section 4 to
    "keep intact all notices".

    c) You must license the entire work, as a whole, under this
    License to anyone who comes into possession of a copy.  This
    License will therefore apply, along with any applicable section 7
    additional terms, to the whole of the work, and all its parts,
    regardless of how they are packaged.  This License gives no
    permission to license the work in any other way, but it does not
    invalidate such permission if you have separately received it.

    d) If the work has interactive user interfaces, each must display
    Appropriate Legal Notices; however, if the Program has interactive
    interfaces that do not display Appropriate Legal Notices, your
    work need not make them do so.

  A compilation of a covered work with other separate and independent
works, which are not by their nature extensions of the covered work,
and which are not combined with it such as to form a larger program,
in or on a volume of a storage or distribution medium, is called an
"aggregate" if the compilation and its resulting copyright are not
used to limit the access or legal rights of the compilation's users
beyond what the individual works permit.  Inclusion of a covered work
in an aggregate does not cause this License to apply to the other
parts of the aggregate.

  6. Conveying Non-Source Forms.

  You may convey a covered work in object code form under the terms
of sections 4 and 5, provided that you also convey the
machine-readable Corresponding Source under the terms of this License,
in one of these ways:

    a) Convey the object code in, or embodied in, a physical product
    (including a physical distribution medium), accompanied by the
    Corresponding Source fixed on a durable physical medium
    customarily used for software interchange.

    b) Convey the object code in, or embodied in, a physical product
    (including a physical distribution medium), accompanied by a
    written offer, valid for at least three years and valid for as
    long as you offer spare parts or customer support for that product
    model, to give anyone who possesses the object code either (1) a
    copy of the Corresponding Source for all the software in the
    product that is covered by this License, on a durable physical
    medium customarily used for software interchange, for a price no
    more than your reasonable cost of physically performing this
    conveying of source, or (2) access to copy the
    Corresponding Source from a network server at no charge.

    c) Convey individual copies of the object code with a copy of the
    written offer to provide the Corresponding Source.  This
    alternative is allowed only occasionally and noncommercially, and
    only if you received the object code with such an offer, in accord
    with subsection 6b.

    d) Convey the object code by offering access from a designated
    place (gratis or for a charge), and offer equivalent access to the
    Corresponding Source in the same way through the same place at no
    further charge.  You need not require recipients to copy the
    Corresponding Source along with the object code.  If the place to
    copy the object code is a network server, the Corresponding Source
    may be on a different server (operated by you or a third party)
    that supports equivalent copying facilities, provided you maintain
    clear directions next to the object code saying where to find the
    Corresponding Source.  Regardless of what server hosts the
    Corresponding Source, you remain obligated to ensure that it is
    available for as long as needed to satisfy these requirements.

    e) Convey the object code using peer-to-peer transmission, provided
    you inform other peers where the object code and Corresponding
    Source of the work are being offered to the general public at no
    charge under subsection 6d.

  A separable portion of the object code, whose source code is excluded
from the Corresponding Source as a System Library, need not be
included in conveying the object code work.

  A "User Product" is either (1) a "consumer product", which means any
tangible personal property which is normally used for personal, family,
or household purposes, or (2) anything designed or sold for incorporation
into a dwelling.  In determining whether a product is a consumer product,
doubtful cases shall be resolved in favor of coverage.  For a particular
product received by a particular user, "normally used" refers to a
typical or common use of that class of product, regardless of the status
of the particular user or of the way in which the particular user
actually uses, or expects or is expected to use, the product.  A product
is a consumer product regardless of whether the product has substantial
commercial, industrial or non-consumer uses, unless such uses represent
the only significant mode of use of the product.

  "Installation Information" for a User Product means any methods,
procedures, authorization keys, or other information required to install
and execute modified versions of a covered work in that User Product from
a modified version of its Corresponding Source.  The information must
suffice to ensure that the continued functioning of the modified object
code is in no case prevented or interfered with solely because
modification has been made.

  If you convey an object code work under this section in, or with, or
specifically for use in, a User Product, and the conveying occurs as
part of a transaction in which the right of possession and use of the
User Product is transferred to the recipient in perpetuity or for a
fixed term (regardless of how the transaction is characterized), the
Corresponding Source conveyed under this section must be accompanied
by the Installation Information.  But this requirement does not apply
if neither you nor any third party retains the ability to install
modified object code on the User Product (for example, the work has
been installed in ROM).

  The requirement to provide Installation Information does not include a
requirement to continue to provide support service, warranty, or updates
for a work that has been modified or installed by the recipient, or for
the User Product in which it has been modified or installed.  Access to a
network may be denied when the modification itself materially and
adversely affects the operation of the network or violates the rules and
protocols for communication across the network.

  Corresponding Source conveyed, and Installation Information provided,
in accord with this section must be in a format that is publicly
documented (and with an implementation available to the public in
source code form), and must require no special password or key for
unpacking, reading or copying.

  7. Additional Terms.

  "Additional permissions" are terms that supplement the terms of this
License by making exceptions from one or more of its conditions.
Additional permissions that are applicable to the entire Program shall
be treated as though they were included in this License, to the extent
that they are valid under applicable law.  If additional permissions
apply only to part of the Program, that part may be used separately
under those permissions, but the entire Program remains governed by
this License without regard to the additional permissions.

  When you convey a copy of a covered work, you may at your option
remove any additional permissions from that copy, or from any part of
it.  (Additional permissions may be written to require their own
removal in certain cases when you modify the work.)  You may place
additional permissions on material, added by you to a covered work,
for which you have or can give appropriate copyright permission.

  Notwithstanding any other provision of this License, for material you
add to a covered work, you may (if authorized by the copyright holders of
that material) supplement the terms of this License with terms:

    a) Disclaiming warranty or limiting liability differently from the
    terms of sections 15 and 16 of this License; or

    b) Requiring preservation of specified reasonable legal notices or
    author attributions in that material or in the Appropriate Legal
    Notices displayed by works containing it; or

    c) Prohibiting misrepresentation of the origin of that material, or
    requiring that modified versions of such material be marked in
    reasonable ways as different from the original version; or

    d) Limiting the use for publicity purposes of names of licensors or
    authors of the material; or

    e) Declining to grant rights under trademark law for use of some
    trade names, trademarks, or service marks; or

    f) Requiring indemnification of licensors and authors of that
    material by anyone who conveys the material (or modified versions of
    it) with contractual assumptions of liability to the recipient, for
    any liability that these contractual assumptions directly impose on
    those licensors and authors.

  All other non-permissive additional terms are considered "further
restrictions" within the meaning of section 10.  If the Program as you
received it, or any part of it, contains a notice stating that it is
governed by this License along with a term that is a further
restriction, you may remove that term.  If a license document contains
a further restriction but permits relicensing or conveying under this
License, you may add to a covered work material governed by the terms
of that license document, provided that the further restriction does
not survive such relicensing or conveying.

  If you add terms to a covered work in accord with this section, you
must place, in the relevant source files, a statement of the
additional terms that apply to those files, or a notice indicating
where to find the applicable terms.

  Additional terms, permissive or non-permissive, may be stated in the
form of a separately written license, or stated as exceptions;
the above requirements apply either way.

  8. Termination.

  You may not propagate or modify a covered work except as expressly
provided under this License.  Any attempt otherwise to propagate or
modify it is void, and will automatically terminate your rights under
this License (including any patent licenses granted under the third
paragraph of section 11).

  However, if you cease all violation of this License, then your
license from a particular copyright holder is reinstated (a)
provisionally, unless and until the copyright holder explicitly and
finally terminates your license, and (b) permanently, if the copyright
holder fails to notify you of the violation by some reasonable means
prior to 60 days after the cessation.

  Moreover, your license from a particular copyright holder is
reinstated permanently if the copyright holder notifies you of the
violation by some reasonable means, this is the first time you have
received notice of violation of this License (for any work) from that
copyright holder, and you cure the violation prior to 30 days after
your receipt of the notice.

  Termination of your rights under this section does not terminate the
licenses of parties who have received copies or rights from you under
this License.  If your rights have been terminated and not permanently
reinstated, you do not qualify to receive new licenses for the same
material under section 10.

  9. Acceptance Not Required for Having Copies.

  You are not required to accept this License in order to receive or
run a copy of the Program.  Ancillary propagation of a covered work
occurring solely as a consequence of using peer-to-peer transmission
to receive a copy likewise does not require acceptance.  However,
nothing other than this License grants you permission to propagate or
modify any covered work.  These actions infringe copyright if you do
not accept this License.  Therefore, by modifying or propagating a
covered work, you indicate your acceptance of this License to do so.

  10. Automatic Licensing of Downstream Recipients.

  Each time you convey a covered work, the recipient automatically
receives a license from the original licensors, to run, modify and
propagate that work, subject to this License.  You are not responsible
for enforcing compliance by third parties with this License.

  An "entity transaction" is a transaction transferring control of an
organization, or substantially all assets of one, or subdividing an
organization, or merging organizations.  If propagation of a covered
work results from an entity transaction, each party to that
transaction who receives a copy of the work also receives whatever
licenses to the work the party's predecessor in interest had or could
give under the previous paragraph, plus a right to possession of the
Corresponding Source of the work from the predecessor in interest, if
the predecessor has it or can get it with reasonable efforts.

  You may not impose any further restrictions on the exercise of the
rights granted or affirmed under this License.  For example, you may
not impose a license fee, royalty, or other charge for exercise of
rights granted under this License, and you may not initiate litigation
(including a cross-claim or counterclaim in a lawsuit) alleging that
any patent claim is infringed by making, using, selling, offering for
sale, or importing the Program or any portion of it.

  11. Patents.

  A "contributor" is a copyright holder who authorizes use under this
License of the Program or a work on which the Program is based.  The
work thus licensed is called the contributor's "contributor version".

  A contributor's "essential patent claims" are all patent claims
owned or controlled by the contributor, whether already acquired or
hereafter acquired, that would be infringed by some manner, permitted
by this License, of making, using, or selling its contributor version,
but do not include claims that would be infringed only as a
consequence of further modification of the contributor version.  For
purposes of this definition, "control" includes the right to grant
patent sublicenses in a manner consistent with the requirements of
this License.

  Each contributor grants you a non-exclusive, worldwide, royalty-free
patent license under the contributor's essential patent claims, to
make, use, sell, offer for sale, import and otherwise run, modify and
propagate the contents of its contributor version.

  In the following three paragraphs, a "patent license" is any express
agreement or commitment, however denominated, not to enforce a patent
(such as an express permission to practice a patent or covenant not to
sue for patent infringement).  To "grant" such a patent license to a
party means to make such an agreement or commitment not to enforce a
patent against the party.

  If you convey a covered work, knowingly relying on a patent license,
and the Corresponding Source of the work is not available for anyone
to copy, free of charge and under the terms of this License, through a
publicly available network server or other readily accessible means,
then you must either (1) cause the Corresponding Source to be so
available, or (2) arrange to deprive yourself of the benefit of the
patent license for this particular work, or (3) arrange, in a manner
consistent with the requirements of this License, to extend the patent
license to downstream recipients.  "Knowingly relying" means you have
actual knowledge that, but for the patent license, your conveying the
covered work in a country, or your recipient's use of the covered work
in a country, would infringe one or more identifiable patents in that
country that you have reason to believe are valid.

  If, pursuant to or in connection with a single transaction or
arrangement, you convey, or propagate by procuring conveyance of, a
covered work, and grant a patent license to some of the parties
receiving the covered work authorizing them to use, propagate, modify
or convey a specific copy of the covered work, then the patent license
you grant is automatically extended to all recipients of the covered
work and works based on it.

  A patent license is "discriminatory" if it does not include within
the scope of its coverage, prohibits the exercise of, or is
conditioned on the non-exercise of one or more of the rights that are
specifically granted under this License.  You may not convey a covered
work if you are a party to an arrangement with a third party that is
in the business of distributing software, under which you make payment
to the third party based on the extent of your activity of conveying
the work, and under which the third party grants, to any of the
parties who would receive the covered work from you, a discriminatory
patent license (a) in connection with copies of the covered work
conveyed by you (or copies made from those copies), or (b) primarily
for and in connection with specific products or compilations that
contain the covered work, unless you entered into that arrangement,
or that patent license was granted, prior to 28 March 2007.

  Nothing in this License shall be construed as excluding or limiting
any implied license or other defenses to infringement that may
otherwise be available to you under applicable patent law.

  12. No Surrender of Others' Freedom.

  If conditions are imposed on you (whether by court order, agreement or
otherwise) that contradict the conditions of this License, they do not
excuse you from the conditions of this License.  If you cannot convey a
covered work so as to satisfy simultaneously your obligations under this
License and any other pertinent obligations, then as a consequence you may
not convey it at all.  For example, if you agree to terms that obligate you
to collect a royalty for further conveying from those to whom you convey
the Program, the only way you could satisfy both those terms and this
License would be to refrain entirely from conveying the Program.

  13. Remote Network Interaction; Use with the GNU General Public License.

  Notwithstanding any other provision of this License, if you modify the
Program, your modified version must prominently offer all users
interacting with it remotely through a computer network (if your version
supports such interaction) an opportunity to receive the Corresponding
Source of your version by providing access to the Corresponding Source
from a network server at no charge, through some standard or customary
means of facilitating copying of software.  This Corresponding Source
shall include the Corresponding Source for any work covered by version 3
of the GNU General Public License that is incorporated pursuant to the
following paragraph.

  Notwithstanding any other provision of this License, you have
permission to link or combine any covered work with a work licensed
under version 3 of the GNU General Public License into a single
combined work, and to convey the resulting work.  The terms of this
License will continue to apply to the part which is the covered work,
but the work with which it is combined will remain governed by version
3 of the GNU General Public License.

  14. Revised Versions of this License.

  The Free Software Foundation may publish revised and/or new versions of
the GNU Affero General Public License from time to time.  Such new versions
will be similar in spirit to the present version, but may differ in detail to
address new problems or concerns.

  Each version is given a distinguishing version number.  If the
Program specifies that a certain numbered version of the GNU Affero General
Public License "or any later version" applies to it, you have the
option of following the terms and conditions either of that numbered
version or of any later version published by the Free Software
Foundation.  If the Program does not specify a version number of the
GNU Affero General Public License, you may choose any version ever published
by the Free Software Foundation.

  If the Program specifies that a proxy can decide which future
versions of the GNU Affero General Public License can be used, that proxy's
public statement of acceptance of a version permanently authorizes you
to choose that version for the Program.

  Later license versions may give you additional or different
permissions.  However, no additional obligations are imposed on any
author or copyright holder as a result of your choosing to follow a
later version.

  15. Disclaimer of Warranty.

  THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY
OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM
IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF
ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

  16. Limitation of Liability.

  IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS
THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY
GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE
USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF
DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD
PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),
EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGES.

  17. Interpretation of Sections 15 and 16.

  If the disclaimer of warranty and limitation of liability provided
above cannot be given local legal effect according to their terms,
reviewing courts shall apply local law that most closely approximates
an absolute waiver of all civil liability in connection with the
Program, unless a warranty or assumption of liability accompanies a
copy of the Program in return for a fee.

                     END OF TERMS AND CONDITIONS

            How to Apply These Terms to Your New Programs

  If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these terms.

  To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

Also add information on how to contact you by electronic and paper mail.

  If your software can interact with users remotely through a computer
network, you should also make sure that it provides a way for users to
get its source.  For example, if your program is a web application, its
interface could display a "Source" link that leads users to an archive
of the code.  There are many ways you could offer source, and different
solutions will be better for different programs; see section 13 for the
specific requirements.

  You should also get your employer (if you work as a programmer) or school,
if any, to sign a "copyright disclaimer" for the program, if necessary.
For more information on this, and how to apply and follow the GNU AGPL, see
<https://www.gnu.org/licenses/>.
AGPL_EOF
  fi
}

write_stack_doc() {
  local name="$1" classification="$2" owns="$3" consumes="$4" not_owns="$5" integrate="${6:-}"
  cat > "$1/docs/stack.md" <<STACK_EOF
# ${name} in the Innotel Platform Stack

**Role: ${classification}** — ${8}

This page declares ${name}'s role in the
[**Innotel Platform Stack**](https://github.com/innotelinc/innotel-platform-stack) —
the canonical single-responsibility architecture. The stack is defined in exactly
one place; this page links the platform to it and states what it owns, consumes,
provides, and explicitly does not own.

## Owns

${owns}

## Provides

${9}

## Consumes

${consumes}

## Explicitly does NOT own

${not_owns}

## Service map (${name}-owned)

| Component | Technology | Job |
|---|---|---|
| (fill in) | (fill in) | (fill in) |

## In the ecosystem

| Flow | Path |
|---|---|
| Identity | Cerulean's Authentik → OIDC → ${name} sessions |
| Secrets | Infisical (SecretOps) → \`.env\` derived; never committed |
| Trust | Cerulean issues DNS + per-zone wildcard TLS; NPM Edge fronts public hosts |
| Revenue | Magnate plans/entitlements gate paid seats (optional) |
| Source of truth | This repository's \`docs/stack.md\` points back to the Innotel Platform Stack |

${integrate}

Back to the canonical definition: the
[Innotel Platform Stack](https://github.com/innotelinc/innotel-platform-stack).
STACK_EOF
}

write_readme() {
  local name="$1" tagline="$2" classification="$3" license="$4" upstream="${5:-}" consumes="${6:-}" landing="$7"
  local badge="$license_badge $license"
  local prologue="# ${name}\n\n**${tagline}**\n\n${name} is the Innotel ecosystem's **${classification}** home"
  local about="> **About ${name}** — ${8} **Landing page:** [${landing}](${landing})"

  cat > "$1/README.md" <<README_EOF
<div align="center">

# ${name} — ${tagline}

**${tagline}**

${upstream_blockupstream "$upstream"}

${badge}

</div>

${about}

---

## Why ${name}

| Problem | ${name} answer |
| --- | --- |
| (fill in) | (fill in) |

## What it is

- (fill in)

## Quick start

\`\`\`bash
git clone ${github_url "$name"}.git
cd ${name}
./scripts/setup.sh
\`\`\`

## Documentation

| Doc | What it covers |
| --- | --- |
| [docs/stack.md](docs/stack.md) | ${name}'s role in the Innotel Platform Stack (${classification}) |
| (add more) | (add more) |

## Repo layout

\`\`\`
${name}/
├── docs/                      # Architecture, Integrations, Deployment, stack role
├── web/landing/               # Static GitHub Pages landing page
├── .github/workflows/         # CI, attribution guard, Pages, release
├── .githooks/                 # Attribution guard (commit-msg, pre-commit, guard-lib)
├── docker-compose.yml         # Compose stack (if applicable)
├── Makefile                   # Operator workflow
├── .env.example               # Environment template
└── LICENSE
\`\`\`

## License

${9}

*${name} — ${tagline}. © ${YEAR}*

## 🏛️ Platform stack

${name} is the ecosystem's **${classification}** platform in the
[**Innotel Platform Stack**](https://github.com/innotelinc/innotel-platform-stack) —
the canonical single-responsibility architecture where Authentik owns identity,
Infisical owns secrets, Cerulean owns trust, ONYX owns storage, Magnate owns
revenue, NPM Edge owns the edge, and every other platform is a business function
that consumes them. See [docs/stack.md](docs/stack.md) for this platform's
owns/consumes boundaries.

${10}
README_EOF
}

# ── upstream prose for the README prologue ─────────────────────────────────────

upstream_blockupstream() {
  local u="$1"
  if [ -z "$u" ]; then
    echo "**${name} — ${tagline}.**"
    return
  fi
  # Very light; full prose is written by the caller.
  :
}

# ── audit ──────────────────────────────────────────────────────────────────────

check() {
  local label="$1" status="$2"
  if [ "$status" = true ]; then
    echo "  ✓ ${label}"
  else
    echo "  ✗ ${label}"
    failures=$((failures+1))
  fi
}

audit() {
  local dir="$1"
  local name
  name="$(basename "$dir")"
  local failures=0
  local _ok _c _gi_matches

  heading "Auditing ${dir} (${name})"

  _ok=$([ -f "$dir/README.md" ] && echo ok || true)
  [ "$_ok" = ok ] && check "README.md exists" true || check "README.md exists" false
  _ok=$([ -f "$dir/LICENSE" ] && echo ok || true)
  [ "$_ok" = ok ] && check "LICENSE exists" true || check "LICENSE exists" false
  # LICENSE must be COMMITTED (a fresh clone only has tracked files) — a
  # file that merely exists locally but is gitignored fails CI audits.
  _ok=$(git -C "$dir" check-ignore -q LICENSE 2>/dev/null && echo ignored || echo ok)
  [ "$_ok" = ok ] && check "LICENSE is tracked (not gitignored)" true || check "LICENSE is tracked (not gitignored)" false
  # LICENSE must be the full canonical text — GitHub license detection returns
  # NOASSERTION for stub notices, which breaks the repo-page license badge.
  _lc=$(wc -l < "$dir/LICENSE" 2>/dev/null || echo 0)
  if grep -qi 'GNU AFFERO GENERAL PUBLIC LICENSE' "$dir/LICENSE" 2>/dev/null; then
    _ok=$([ "$_lc" -ge 400 ] && grep -qi 'END OF TERMS AND CONDITIONS' "$dir/LICENSE" && echo ok || true)
  elif grep -qi 'MIT License' "$dir/LICENSE" 2>/dev/null; then
    _ok=$([ "$_lc" -ge 15 ] && grep -qi 'THE SOFTWARE IS PROVIDED' "$dir/LICENSE" && echo ok || true)
  else
    _ok=
  fi
  [ "$_ok" = ok ] && check "LICENSE is canonical full text (GitHub-detectable)" true || check "LICENSE is canonical full text (GitHub-detectable)" false
  _ok=$([ -f "$dir/.env.example" ] && echo ok || true)
  [ "$_ok" = ok ] && check ".env.example exists" true || check ".env.example exists" false
  # .env.example must be COMMITTED — a fresh clone only has tracked files.
  _ok=$(git -C "$dir" check-ignore -q .env.example 2>/dev/null && echo ignored || echo ok)
  [ "$_ok" = ok ] && check ".env.example is tracked (not gitignored)" true || check ".env.example is tracked (not gitignored)" false
  _ok=$([ -f "$dir/.gitignore" ] && echo ok || true)
  [ "$_ok" = ok ] && check ".gitignore exists" true || check ".gitignore exists" false

  _gi_matches=$(grep -c '^\.env' "$dir/.gitignore" 2>/dev/null || true)
  [ "$_gi_matches" -gt 0 ] && check ".gitignore covers .env" true || check ".gitignore covers .env" false
  _ok=$([ -f "$dir/web/landing/index.html" ] && echo ok || true)
  [ "$_ok" = ok ] && check "web/landing/index.html exists" true || check "web/landing/index.html exists" false
  _ok=$([ -f "$dir/docs/stack.md" ] && echo ok || true)
  [ "$_ok" = ok ] && check "docs/stack.md exists" true || check "docs/stack.md exists" false
  _ok=$([ -f "$dir/.github/workflows/attribution-guard.yml" ] && echo ok || true)
  [ "$_ok" = ok ] && check ".github/workflows/attribution-guard.yml" true || check ".github/workflows/attribution-guard.yml" false
  _ok=$([ -f "$dir/.githooks/guard-lib" ] && echo ok || true)
  [ "$_ok" = ok ] && check ".githooks/guard-lib exists" true || check ".githooks/guard-lib exists" false
  if [ -f "$dir/Makefile" ]; then
    check "Makefile exists (or intentionally absent)" true
  else
    echo "  (no Makefile — OK if not a compose/compute repo)"
  fi


  # landing sanity
  if [ -f "$dir/web/landing/index.html" ]; then
    _c=$(grep -ci '<title>' "$dir/web/landing/index.html" || true)
    [ "$_c" -gt 0 ] && check "landing has <title>" true || check "landing has <title>" false
    _c=$(grep -ci 'og:title' "$dir/web/landing/index.html" || true)
    [ "$_c" -gt 0 ] && check "landing has og:title" true || check "landing has og:title" false
    _c=$(grep -ci 'data:image/svg+xml' "$dir/web/landing/index.html" || true)
    [ "$_c" -gt 0 ] && check "landing is self-contained SVG favicon" true || check "landing is self-contained SVG favicon" false

    if grep -Eiq 'generated with|generated by|co-authored-by' "$dir/web/landing/index.html"; then
      echo "  WARNING: landing may contain attribution text"
      failures=$((failures+1))
    else
      check "landing declares no AI attribution" true
    fi
  fi

  # README shape
  if [ -f "$dir/README.md" ]; then
    _c=$(grep -c 'actions/workflows/ci.yml/badge.svg' "$dir/README.md" || true)
    [ "$_c" -gt 0 ] && check "README has CI badge" true || check "README has CI badge" false
    _c=$(grep -ci 'badge.*license' "$dir/README.md" || true)
    [ "$_c" -gt 0 ] && check "README has license badge" true || check "README has license badge" false
    _c=$(grep -ci '^| Problem ' "$dir/README.md" || true)
    [ "$_c" -gt 0 ] && check "README has Why table" true || check "README has Why table" false
    _c=$(grep -c 'docs/stack.md' "$dir/README.md" || true)
    [ "$_c" -gt 0 ] && check "README links to docs/stack.md" true || check "README links to docs/stack.md" false
    _c=$(grep -c 'innotelinc/innotel-platform-stack' "$dir/README.md" || true)
    [ "$_c" -gt 0 ] && check "README links to Innotel Platform Stack" true || check "README links to Innotel Platform Stack" false
    _c=$(grep -ci '^## License' "$dir/README.md" || true)
    [ "$_c" -gt 0 ] && check "README has License section" true || check "README has License section" false
  fi

  # attribution guard content
  if [ -f "$dir/.githooks/guard-lib" ]; then
    _c=$(grep -c 'TOOL_TOKEN=' "$dir/.githooks/guard-lib" || true)
    [ "$_c" -gt 0 ] && check "guard-lib is the shared policy (contains TOOL_TOKEN)" true || check "guard-lib is the shared policy (contains TOOL_TOKEN)" false
  fi

  # .env.example posture
  if [ -f "$dir/.env.example" ]; then
    if grep -qiE 'never commit.*\.env|\.env.*gitignored|gitignored' "$dir/.env.example"; then
      check ".env.example states never commit .env" true
    else
      echo "  (no explicit .env-ignore note — recommended)"
    fi
    _c=$(grep -ci 'cerulean' "$dir/.env.example" || true)
    [ "$_c" -gt 0 ] && check ".env.example references Cerulean" true || check ".env.example references Cerulean" false
    check ".env.example references Magnate (if billing)" true
    if grep -qi 'infisical' "$dir/.env.example"; then
      check ".env.example references Infisical" true
    else
      echo "  (no Infisical note — recommended)"
    fi
  fi

  # CI
  if [ -f "$dir/.github/workflows/ci.yml" ]; then
    check "ci.yml exists" true
  else
    echo "  NOTE: no ci.yml — attribution guard only is conformant but ci.yml is preferred"
  fi

  echo
  if [ "$failures" -eq 0 ]; then
    echo "conform: ${name} — conforms (or close; review notes above)."
  else
    echo "conform: ${name} — ${failures} conformity issue(s) above."
  fi
}

# ── scaffold ───────────────────────────────────────────────────────────────────

scaffold() {
  local name="$1" classification="$2"
  local dir="$(pwd)/${name}"

  if [ -e "$dir" ]; then
    die "directory already exists: ${dir}"
  fi

  heading "Scaffolding ${dir} (${name}, ${classification})"

  mkdir -p "$dir"/{docs,.github/workflows,.githooks,web/landing,scripts}
  cd "$dir"

  write_guard_lib            "$dir"
  write_commit_msg_hook      "$dir"
  write_pre_commit_hook      "$dir"
  write_attribution_guard_ci "$dir"
  write_ci_yml               "$dir"
  write_pages_yml            "$dir"
  write_makefile             "$dir" "$name" "$classification"

  # Landing placeholder — conformant outline, platform-specific bits unfilled.
  write_landing              "$dir" "$name" "$classification"

  write_readme               "$dir" "$name" \
    "${classification} platform" "$classification" \
    "MIT" \
    "" \
    "" \
    "$(pages_url "$name")" \
    "TODO: one-paragraph about." \
    "TODO: license paragraph (state the repo's license and how upstreams are retained)." \
    "" \
    ""

  write_env_example          "$dir" "$classification" "${name}.innotel.us" "${name}"
  write_license              "$dir" "MIT"
  write_stack_doc            "$dir" "$name" "$classification" \
    "- (fill in what ${name} owns)" \
    "- Cerulean (Authentik SSO, DNS, TLS)\n- Infisical (secrets)\n- Magnate (billing, optional)\n- NPM Edge (public hosts)" \
    "- Identity (Authentik)\n- Secrets (Infisical)\n- DNS/TLS (Cerulean)\n- Billing (Magnate)" \
    "" \
    "" \
    "- (fill in what ${name} provides to the ecosystem)" \
    "- (fill in what ${name} explicitly does not own)"

  cat > "$dir/.gitignore" <<'GITIGNORE_EOF'
.env
.env.local
data/
backups/
*.sqlite
*.tar.gz
GITIGNORE_EOF

  cat > "$dir/scripts/setup.sh" <<'SETUP_EOF'
#!/usr/bin/env bash
# ${name} — one-shot bootstrap: guard hooks + .env with generated secrets.
set -euo pipefail

APP="$(basename "$(pwd)")"
echo "==> ${APP} bootstrap"

# Install the attribution guard hooks locally.
if [ -d .githooks ]; then
  git config core.hooksPath .githooks
  echo "==> attribution guard hooks installed (.githooks)"
fi

if [ ! -f .env ]; then
  if [ -f .env.example ]; then
    cp .env.example .env
    echo "==> .env copied from .env.example — fill in real values"
  fi
fi

echo "==> done. Next: review .env, then \`make up\` (or \`docker compose up -d\`)."
SETUP_EOF
  chmod +x "$dir/scripts/setup.sh"

  cat > "$dir/docker-compose.yml" <<COMPOSE_EOF
# ${name} — operator compose (optional; delete if this repo is not a Compose stack).
#
# Conformity note: a conformant repo that runs services owns this file + a
# Makefile \`up\` target. If ${name} is pure code/docs with no local services,
# remove this file and the \`docker compose\` targets from the Makefile.
COMPOSE_EOF

  cd - >/dev/null

  echo
  echo "conform: scaffolded ${dir}."
  echo "next steps:"
  echo "  1. cd ${dir} && fill in README + docs/stack.md + web/landing + docker-compose.yml"
  echo "  2. git init && git add -A && git commit -m 'initial: scaffold ${name}'"
  echo "  3. enable GitHub Pages (repo Settings -> Pages -> Source: GitHub Actions)"
  echo "  4. push and verify https://innotelinc.github.io/${name}/"
}

write_landing() {
  local dir="$1" name="$2" classification="$3"
  local accent="#22d3ee"  # default Atlas-like cyan; override per platform

  cat > "$dir/web/landing/index.html" <<LANDING_EOF
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${name} — ${classification} Platform</title>
  <meta name="description" content="TODO: one-sentence description of ${name}.">
  <meta property="og:title" content="${name} — ${classification} Platform">
  <meta property="og:description" content="TODO: one-sentence description for social.">
  <meta property="og:type" content="website">
  <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='%230b0d10'/%3E%3Ctext x='32' y='44' font-size='34' text-anchor='middle'%3E${icon_char "${name}" '%2322d3ee'}%3C/text%3E%3C/svg%3E">
  <style>
    :root {
      color-scheme: dark;
      --p-bg: #0b0d10;
      --p-bg-elevated: #12151a;
      --p-surface: #181c22;
      --p-surface-hover: #1f242c;
      --p-border: #262c35;
      --p-text: #f4f7fb;
      --p-text-secondary: #cdd6e0;
      --p-text-muted: #a8b2bf;
      --p-accent: ${accent};
      --p-accent-hover: #67e8f9;
      --p-accent-tint: rgba(34, 211, 238, 0.12);
      --p-gold: #f5b544;
      --p-success: #3ddc84;
      --radius-sm: 6px;
      --radius-md: 10px;
      --radius-lg: 16px;
      --ease: cubic-bezier(.2, .8, .2, 1);
    }
    * { box-sizing: border-box; }
    html { scroll-behavior: smooth; }
    body {
      margin: 0; background: var(--p-bg); color: var(--p-text);
      font-family: ui-sans-serif, system-ui, "Segoe UI", Roboto, "Helvetica Neue", sans-serif;
      font-size: 16px; line-height: 1.6; -webkit-font-smoothing: antialiased;
    }
    ::selection { background: var(--p-accent-tint); }
    a { color: var(--p-accent); text-decoration: none; }
    a:hover { color: var(--p-accent-hover); }
    code, pre { font-family: "JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
    .wrap { max-width: 1080px; margin: 0 auto; padding: 0 24px; }

    .topbar { position: sticky; top: 0; z-index: 10; background: rgba(10, 14, 19, 0.72); backdrop-filter: blur(24px); -webkit-backdrop-filter: blur(24px); border-bottom: 1px solid var(--p-border); }
    .topbar-inner { display: flex; align-items: center; gap: 20px; height: 60px; }
    .brand { display: flex; align-items: center; gap: 10px; font-weight: 650; letter-spacing: 0.04em; color: var(--p-text); }
    .brand:hover { color: var(--p-text); }
    .brand .mark { display: grid; place-items: center; width: 26px; height: 26px; border-radius: 8px; background: var(--p-bg-elevated); border: 1px solid var(--p-border); font-size: 15px; }
    .brand .dot { color: var(--p-accent); }
    .topbar nav { margin-left: auto; display: flex; align-items: center; gap: 4px; }
    .topbar nav a { color: var(--p-text-secondary); padding: 6px 12px; border-radius: var(--radius-sm); font-size: 14px; transition: color .15s var(--ease), background .15s var(--ease); }
    .topbar nav a:hover { color: var(--p-text); background: var(--p-surface-hover); }
    .topbar .gh { display: inline-flex; align-items: center; gap: 8px; margin-left: 8px; border: 1px solid var(--p-border); border-radius: var(--radius-md); padding: 7px 14px; color: var(--p-text); font-size: 14px; transition: border-color .15s var(--ease), background .15s var(--ease); }
    .topbar .gh:hover { border-color: var(--p-accent); background: var(--p-accent-tint); color: var(--p-text); }

    .hero { position: relative; overflow: hidden; padding: 96px 0 72px; }
    .hero::before { content: ""; position: absolute; inset: 0; background: radial-gradient(600px 320px at 70% -10%, rgba(34, 211, 238, 0.14), transparent 70%), radial-gradient(500px 300px at 15% 110%, rgba(245, 181, 68, 0.06), transparent 70%); pointer-events: none; }
    .hero-inner { position: relative; max-width: 760px; }
    .kicker { display: inline-flex; align-items: center; gap: 8px; font-size: 13px; letter-spacing: 0.08em; text-transform: uppercase; color: var(--p-accent-hover); background: var(--p-accent-tint); border: 1px solid rgba(34, 211, 238, 0.3); border-radius: 999px; padding: 5px 14px; margin: 0 0 24px; }
    .kicker .pulse { width: 7px; height: 7px; border-radius: 50%; background: var(--p-success); box-shadow: 0 0 0 0 rgba(61, 220, 132, 0.5); animation: pulse 2.4s var(--ease) infinite; }
    @keyframes pulse { 0% { box-shadow: 0 0 0 0 rgba(61, 220, 132, 0.45); } 70% { box-shadow: 0 0 0 9px rgba(61, 220, 132, 0); } 100% { box-shadow: 0 0 0 0 rgba(61, 220, 132, 0); } }
    h1 { font-size: clamp(2.2rem, 5.5vw, 3.4rem); line-height: 1.08; letter-spacing: -0.02em; margin: 0 0 20px; font-weight: 700; }
    h1 .accent { color: var(--p-accent); }
    .lede { font-size: 1.125rem; color: var(--p-text-secondary); max-width: 660px; margin: 0 0 32px; }
    .cta-row { display: flex; flex-wrap: wrap; gap: 12px; margin-bottom: 28px; }
    .btn { display: inline-flex; align-items: center; gap: 8px; border-radius: var(--radius-md); padding: 11px 20px; font-size: 15px; font-weight: 550; border: 1px solid transparent; cursor: pointer; transition: background .15s var(--ease), border-color .15s var(--ease); }
    .btn-primary { background: var(--p-accent); color: #0a0e13; font-weight: 600; }
    .btn-primary:hover { background: var(--p-accent-hover); color: #0a0e13; }
    .btn-secondary { border-color: var(--p-border); color: var(--p-text); background: transparent; }
    .btn-secondary:hover { border-color: var(--p-accent); background: var(--p-accent-tint); color: var(--p-text); }
    .quickstart { display: flex; align-items: center; gap: 14px; background: var(--p-bg-elevated); border: 1px solid var(--p-border); border-radius: var(--radius-md); padding: 12px 16px; max-width: 680px; font-size: 13.5px; }
    .quickstart code { color: var(--p-text); white-space: nowrap; overflow-x: auto; }
    .quickstart code .c { color: var(--p-text-muted); }
    .quickstart .copy { margin-left: auto; flex: 0 0 auto; background: transparent; border: 1px solid var(--p-border); color: var(--p-text-secondary); border-radius: var(--radius-sm); font: inherit; font-size: 12px; padding: 4px 10px; cursor: pointer; transition: border-color .15s var(--ease), color .15s var(--ease); }
    .quickstart .copy:hover { border-color: var(--p-accent); color: var(--p-text); }
    .quickstart .copy.copied { color: var(--p-success); border-color: var(--p-success); }

    .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 12px; margin: 56px 0 0; }
    .stat { background: var(--p-bg-elevated); border: 1px solid var(--p-border); border-radius: var(--radius-md); padding: 16px; }
    .stat .n { font-size: 1.5rem; font-weight: 700; letter-spacing: -0.02em; }
    .stat .n em { font-style: normal; color: var(--p-accent); }
    .stat .l { font-size: 13px; color: var(--p-text-muted); margin-top: 2px; }

    section { padding: 64px 0; }
    .sec-head { display: flex; align-items: baseline; gap: 14px; margin-bottom: 28px; }
    .sec-head h2 { font-size: 1.6rem; letter-spacing: -0.02em; margin: 0; }
    .sec-head p { color: var(--p-text-muted); margin: 0; font-size: 14.5px; }
  </style>
</head>
<body>
  <header class="topbar">
    <div class="wrap">
      <div class="topbar-inner">
        <a class="brand" href="/">
          <span class="mark">${icon_char "${name}" 'var(--p-accent)'}</span>
          <span>${name}</span>
        </a>
        <nav>
          <a href="https://github.com/innotelinc/${name}">Docs</a>
          <a class="gh" href="https://github.com/innotelinc/${name}">GitHub ↗</a>
        </nav>
      </div>
    </div>
  </header>

  <div class="wrap">
    <section class="hero">
      <div class="hero-inner">
        <div class="kicker"><span class="pulse"></span> ${classification} · self-hosted</div>
        <h1>${name} — <span class="accent">${classification}</span>, your way.</h1>
        <p class="lede">TODO: one or two sentences that a visitor can act on — what it does, why it exists, and the first step.</p>
        <div class="cta-row">
          <a class="btn btn-primary" href="https://github.com/innotelinc/${name}">View on GitHub</a>
          <a class="btn btn-secondary" href="https://github.com/innotelinc/${name}/blob/main/README.md">Quick start</a>
        </div>
      </div>
    </section>

    <section>
      <div class="sec-head">
        <h2>Why ${name}</h2>
        <p>The portfolio's signature README element — mirrored on the landing and the README.</p>
      </div>
      <div class="grid" style="display:grid; gap:14px;">
        <div class="card" style="border:1px solid var(--p-border); background:var(--p-bg-elevated); border-radius:var(--radius-md); padding:18px;">
          <h3 style="margin:0 0 6px; font-size:1.02rem;">TODO — Problem A</h3>
          <p style="margin:0; color:var(--p-text-secondary); font-size:14px;">TODO — ${name} answer.</p>
        </div>
        <div class="card" style="border:1px solid var(--p-border); background:var(--p-bg-elevated); border-radius:var(--radius-md); padding:18px;">
          <h3 style="margin:0 0 6px; font-size:1.02rem;">TODO — Problem B</h3>
          <p style="margin:0; color:var(--p-text-secondary); font-size:14px;">TODO — ${name} answer.</p>
        </div>
      </div>
    </section>

    <section>
      <div class="sec-head">
        <h2>What it is</h2>
        <p>Fill in the ${name}-owned surfaces.</p>
      </div>
      <div class="grid" style="display:grid; gap:14px;">
        <div class="card" style="border:1px solid var(--p-border); background:var(--p-bg-elevated); border-radius:var(--radius-md); padding:18px;">
          <h3 style="margin:0 0 6px; font-size:1.02rem;">TODO — surface 1</h3>
          <p style="margin:0; color:var(--p-text-secondary); font-size:14px;">TODO.</p>
        </div>
        <div class="card" style="border:1px solid var(--p-border); background:var(--p-bg-elevated); border-radius:var(--radius-md); padding:18px;">
          <h3 style="margin:0 0 6px; font-size:1.02rem;">TODO — surface 2</h3>
          <p style="margin:0; color:var(--p-text-secondary); font-size:14px;">TODO.</p>
        </div>
      </div>
    </section>

    <footer>
      <div class="wrap" style="max-width:1080px; margin:0 auto; padding:0 24px; margin-top:60px; border-top:1px solid var(--p-border); padding-top:18px; color:var(--p-text-muted); font-size:13px;">
        <div>© ${YEAR} ${name} — ${classification}. © ${YEAR}</div>
        <div style="margin-top:6px;"><a href="https://github.com/innotelinc/${name}">GitHub</a> · <a href="https://github.com/innotelinc/innotel-platform-stack">Innotel Platform Stack</a></div>
      </div>
    </footer>
  </div>
</body>
</html>
LANDING_EOF
}

icon_char() {
  # crude product-icon picker by name — override per platform.
  case "${1,,}" in
    atlas)      echo '🗺️' ;;
    distro)     echo '📦' ;;
    cerulean)   echo '🔵' ;;
    magnate)    echo '💎' ;;
    zeus)       echo '⚡' ;;
    capstone)   echo '🎙️' ;;
    monarch)    echo '🦋' ;;
    oasis)      echo '🌴' ;;
    signara)    echo '✍️' ;;
    rizzaura)   echo '🔥' ;;
    atheniq)    echo '🎓' ;;
    onyx)       echo '🗄️' ;;
    zapit)      echo '⚡' ;;
    *)          echo '•' ;;
  esac
}

# ── main ───────────────────────────────────────────────────────────────────────

main() {
  if [ "${1:-}" = "--new" ]; then
    [ -n "${2:-}" ] || die "usage: conform-project.sh --new <name> <classification>"
    [ -n "${3:-}" ] || die "usage: conform-project.sh --new <name> <classification>"
    scaffold "$2" "$3"
  else
    [ -n "${1:-}" ] || die "usage: conform-project.sh <repo-dir>   (or --new <name> <classification>)"
    audit "$1"
  fi
}

main "$@"
